### ISSUE TITLE
Re-license under Apache-2 / MIT dual license

### ISSUE THREAD

**Issue by yoshuawuyts** [ZhouHansen/atomic-batcher#1]
Heya!

Awesome work on this module! Could we perhaps change the license to a dual license under `APACHE-2` / `MIT` so it can be in line with the rest of the project. While I like the AGPL license a lot, an explicit choice was made for a more permissive license, so it integrates well with the rest of the Rust ecosystem, and won't run into any problems being integrated into upstream projects (particularly eyeing browsers here).

Hope this makes sense!

Thanks heaps!

**Comment by ZhouHansen** [comment]
Thanks, done

**Comment by yoshuawuyts** [comment]
@ZhouHansen yay, thanks so much!
